### ISSUE TITLE
brew install cpp-ethereum fails on OSX 10.11

### ISSUE THREAD

**Issue by jwhelan72** [ethereum/homebrew-ethereum#48]
cpp-ethereum fails to build correctly for me.  The following errors are reported:

    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [libethereum/libethash/libethash.dylib] Error 1 
    make[1]: *** [libethereum/libethash/CMakeFiles/ethash.dir/all] Error 2
    [  6%] Built target natspec
    make: *** [all] Error 2

I've searched extensively for a solution but have failed to resolve the issue.

**Comment by pwrstudio** [comment]
Same general problem here: fails to build on OSX 10.11.2 with the following messages:

```
$ brew install cpp-ethereum --debug
==> Tapping ethereum/ethereum
Cloning into '/usr/local/Library/Taps/ethereum/homebrew-ethereum'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Tapped 2 formulae (29 files, 128K)
Rasmuss-Air:~ rasmus$ brew install cpp-ethereum --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
Warning: ethereum/ethereum/cpp-ethereum-1.0rc2 already installed
Rasmuss-Air:~ rasmus$ brew reinstall cpp-ethereum --debug
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/pwrstudio/homebrew-ethereum/cpp-ethereum.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
==> Reinstalling ethereum/ethereum/cpp-ethereum
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/sphinx-doc.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cryptopp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/miniupnpc.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/leveldb.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/snappy.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/gmp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/curl.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libjson-rpc-cpp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/argtable.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/jsoncpp.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libmicrohttpd.rb
/usr/local/Library/brew.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/v8-315.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cryptopp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/miniupnpc.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/leveldb.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/snappy.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/gmp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/curl.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libjson-rpc-cpp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/argtable.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/jsoncpp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libmicrohttpd.rb
/usr/local/Library/Homebrew/build.rb (Formulary::TapLoader): loading /usr/local/Library/Taps/homebrew/homebrew-versions/v8-315.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/sphinx-doc.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/git.rb
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.0rc2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE
Last 15 lines from /Users/rasmus/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
-- LevelDB headers: /usr/local/include
-- LevelDB lib   : /usr/local/lib/libleveldb.dylib
CMake Error at webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP: Found unsuitable version "5.6.3", but required is
  exact version "5.6.2" (found /usr/local/include)
Call Stack (most recent call first):
  webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:372 (_FPHSA_FAILURE_MESSAGE)
  webthree-helpers/cmake/FindCryptoPP.cmake:107 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  webthree-helpers/cmake/UseCryptopp.cmake:2 (find_package)
  webthree-helpers/cmake/EthDependencies.cmake:105 (eth_apply)
  libweb3core/libdevcrypto/CMakeLists.txt:8 (eth_use)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum20151225-72385-1cmrunc/CMakeFiles/CMakeOutput.log".
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.0rc2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release -DEVMJIT=0 -DGUI=0
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/ethereum/issues 
```

I suspect this has something to do with having a too old version of LLVM. Tried installing with `brew install llvm --HEAD --with-clang`. Successful, but cpp-ethereum still fails to install. 

I tired using the modified formula file here:
https://gist.github.com/iPadGuy/8eb95b7b12379412ff24
To make sure the newer homebrew-installed LLVM is used rather than the Xcode one, but still get the same error installing from that.

Anybody got an idea how to solve this? geth is running well, but need the solidity compiler...

**Comment by dreid93** [comment]
@pwrstudio this is because : 

```
CMake Error at webthree-helpers/cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP: Found unsuitable version "5.6.3", but required is
  exact version "5.6.2" (found /usr/local/include)
```
For instructions on how to resolve this see here : https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

@caktux I propose closing this issue and marking it as a duplicate of #49

**Comment by caktux** [comment]
Initial report was related to libethash, only the comment by @pwrstudio is a duplicate. It's never a good idea to checkout a specific commit hash of a formula (@bobsummerwill, did you put that in the wiki?) as it messes the state of your homebrew library. The right solution is for cpp-ethereum to simply update their cmake file and update their code if required.

**Comment by bobsummerwill** [comment]
Hey @caktux!
No - that bit of the instructions was added by @dreid93 two days back:
    https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X/_history
Just undoing that.
See https://github.com/ethereum/webthree-umbrella/issues/117 for the full log of horrors in working through this nonsense.   @area also on the case.

WRT this specific ticket from @jwhelan72, we're missing the full log to be able to work out what is happening, but I suspect that it is ancient history now, and we're better off closing it.    Ditto for a bunch of old OS X issues.    I'll do a full sweep/triage soon.

Perhaps you could re-try, @jwhelan72, if you are still interested in a working OS X build?

**Comment by bobsummerwill** [comment]
Please can we close this, @chriseth, as per https://github.com/ethereum/webthree-umbrella/issues/117?  Thanks!
